"use strict";
import { btnsEvt } from "./utils/next&backbtn.js";
import { yearOrMonth } from "./utils/yearMonthBtn.js";
import { evtPlanType } from "./utils/evtPlanType.js";
import { evtCheckBox } from "./utils/evtCheBox.js";
import { adjustScreen } from "./utils/resp.js";
btnsEvt();
yearOrMonth();
evtPlanType();
evtCheckBox();
adjustScreen();
