"use strict";
import { bntsEvt } from "./utils/next&backbtn.js";
import { yearOrMonth } from "./utils/yearMonthBtn.js";
import { evtPlanType } from "./utils/evtPlanType.js";
import { evtCheckBox } from "./utils/evtCheBox.js";
import { responsive } from "./utils/resp.js";
bntsEvt();
yearOrMonth();
evtPlanType();
evtCheckBox();
responsive();
